### ISSUE TITLE
Fieldstitel Translation

### ISSUE THREAD

**Issue by gino2014** [tmhub/tmhub.github.io#5]
The Titel of the added fields are not translatable, like Company,Person or Housnumber.

**Comment by vovayatsyuk** [comment]
Hi!

Please, indicate what document you are referring to.

**Comment by gino2014** [comment]
Hi,
 i have added this lines to our custom.js from firecheckout extensions, bat the field titles are not translatable, neighter via inline translation nor via translate.csv or TM_FireCheckout.csv.
These are the documents:
https://github.com/tmhub/tmhub.github.io/blob/master/extensions/firecheckout/dependent-fields.md

and

https://github.com/tmhub/tmhub.github.io/blob/master/extensions/firecheckout/housenumber.md

regards
Gino

**Comment by vovayatsyuk** [comment]
Thank you,

These are only examples of how to get the things done with pure javascript and minimum
dependencies.

If you need to use localized versions of the script, you can move the code to any `phtml` template of you theme, and wrap all titles into `$this->__()` calls. For example:

```html
<script>
document.observe('dom:loaded', function() {
    $('billing:firstname').up('li').insert({
        before: [
            '<li class="control" style="padding: 5px 0;">',
                '<input type="radio" id="radio_company" name="radio_company_person"/>',
                '<label for="radio_company" style="margin: 0 4px">'+'<?php echo $this->__('Company') ?>' + '</label>',
                '<input type="radio" id="radio_person" checked="checked" name="radio_company_person"/>',
                '<label for="radio_person" style="margin: 0 4px">' + '<?php echo $this->__('Person') ?>' + '</label>',
            '</li>'
        ].join('')
    });
});
</script>
```
